language: es_core_news_lg
pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
    "intent_tokenization_flag": True
  - name: "SpacyFeaturizer"
    "pooling": "mean"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: DIETClassifier
    epochs: 100
    ranking_length: 5
    use_masked_language_model: True
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat


policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 10
    epochs: 100

