version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.4.3-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: wvalverde67/gc-bot-4:1
    expose: 
      - 5055

